### ISSUE TITLE
requirements.txt required

### ISSUE THREAD

**Issue by yyc001** [dgliu/COLING22_CTM#5]
I'm trying to use your project but noticed that it doesn't include a `requirements.txt` file. Would you be able to add this file and list the required Python dependencies? Thank you!

**Comment by dgliu** [comment]
Hi, some key library information is as follows for reference:

python==3.6.9
tensorflow==1.15.3+nv
optuna==2.10.0
keras==2.3.1
thulac==0.2.1
jieba==0.42.1
numpy==1.17.3
pandas==0.25.3

Note that since our GPU only supports a higher version of CUDA, the TensorFlow used is a specific version provided by Nvidia, please refer to the relevant information for its installation. 

Please feel free to contact me again if you have any other questions.
Best.
